### ISSUE TITLE
Properties are highlighted as cssProp even when used as values

### ISSUE THREAD

**Issue by jsit** [JulesWang/css.vim#81]
Take the following CSS:

```css
div {
  background-color: blue;
  color: white;
  transition: 0.2s background-color, color ease-in-out;
}
```

In the second line, `background-color` is a CSS property being assigned a value. In the fourth line, `background-color` is *part* of the value of `transition`, yet both are assigned to the group `cssBackgroundProp`.

They're related, but different things, and as such it would be nice if they had different highlight groups assigned to them.
